[package]
name = "mason-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
mason-core = { path = "../mason-core" }
rand = "0.9.0"
taffy = {workspace = true}
style_atoms = { workspace = true }