[package]
name = "mason-android"
version = "0.1.0"
edition = "2021"

[lib]
name = "masonandroid"
crate-type = ["cdylib"]

[dependencies]
mason-core = { path = "../mason-core" }
jni = "0.20.0"
log = "0.4.17"
android_logger = "0.11.1"
cxx = "1.0.83"
once_cell = "1.16.0"

[build-dependencies]
cxx-build = "1.0.83"
