[package]
name = "mason-ios"
version = "0.1.0"
edition = "2021"


[lib]
name = "masonnative"
crate-type = ["staticlib"]

[dependencies]
mason-c = { path = "../mason-c" }
mason-core = { path = "../mason-core" }